import pro1 from "../../Assets/pro1.JPG";
import pro2 from "../../Assets/pro2.jpg";
import pro3 from "../../Assets/pro3.png";

export const CardsData = [
  {
    id: 1,
    quantity: 1,
    title: "VOX-SP",
    imgsrc: pro1,
    price: 50,
    discount: 2,
    discountPrice: 50 - (2 / 100) * 50,
    desc: "Vox Tablet is used to treat different types of bacterial infections such as infection of throat, lung, sinus, kidney, urinary tract, skin and soft tissues.",
  },
  {
    id: 2,
    quantity: 2,
    title: "Bascupan",
    imgsrc: pro2,
    price: 100,
    discount: 2,
    discountPrice: 100 - (2 / 100) * 100,
    desc: "Buscopan relieves painful stomach cramps, including those linked with irritable bowel syndrome (IBS). It can also help bladder cramps and period pain. Buscopan contains the active ingredient hyoscine butylbromide.",
  },
  {
    id: 3,
    quantity: 3,

    title: "Panadol",
    imgsrc: pro3,
    price: 150,
    discount: 2,
    discountPrice: 150 - (2 / 100) * 150,
    desc: "Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains,",
  },
  {
    id: 4,
    quantity: 4,
    title: "VOX-SP",
    imgsrc: pro1,
    price: 50,
    discount: 2,
    discountPrice: 50 - (2 / 100) * 50,
    desc: "Vox Tablet is used to treat different types of bacterial infections such as infection of throat, lung, sinus, kidney, urinary tract, skin and soft tissues.",
  },
  {
    id: 5,
    quantity: 5,
    title: "Bascupan",
    imgsrc: pro2,
    price: 100,
    discount: 2,
    discountPrice: 100 - (2 / 100) * 100,
    desc: "Buscopan relieves painful stomach cramps, including those linked with irritable bowel syndrome (IBS). It can also help bladder cramps and period pain. Buscopan contains the active ingredient hyoscine butylbromide.",
  },
  {
    id: 6,
    quantity: 6,
    title: "Panadol",
    imgsrc: pro3,
    price: 150,
    discount: 2,
    discountPrice: 150 - (2 / 100) * 150,
    desc: "Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains,",
  },
  {
    id: 7,
    quantity: 7,
    title: "VOX-SP",
    imgsrc: pro1,
    price: 50,
    discount: 2,
    discountPrice: 50 - (2 / 100) * 50,
    desc: "Vox Tablet is used to treat different types of bacterial infections such as infection of throat, lung, sinus, kidney, urinary tract, skin and soft tissues.",
  },
  {
    id: 8,
    quantity: 8,
    title: "Bascupan",
    imgsrc: pro2,
    price: 100,
    discount: 2,
    discountPrice: 100 - (2 / 100) * 100,
    desc: "Buscopan relieves painful stomach cramps, including those linked with irritable bowel syndrome (IBS). It can also help bladder cramps and period pain. Buscopan contains the active ingredient hyoscine butylbromide.",
  },
  {
    id: 9,
    quantity: 9,
    title: "Panadol",
    imgsrc: pro3,
    price: 150,
    discount: 2,
    discountPrice: 150 - (2 / 100) * 150,
    desc: "Panadol Original Tablets is a mild analgesic and antipyretic, and is recommended for the treatment of most painful and febrile conditions, for example, headache including migraine and tension headaches, toothache, backache, rheumatic and muscle pains,",
  },
];
